# Site settings
title: Personal website of Ömer Kenan Uçmaklıoğlu
description: Personal website of Ömer Kenan Uçmaklıoğlu
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ömer Kenan Uçmaklıoğlu
user_description: I am an engineer who likes to learn, create and discover.
user_title: Electrical and Electronics Engineer
email: omerkenanuc@gmail.com
twitter_username: lorem_ipsum
github_username:  omerkenan
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
